long_name = "Time thief"
short_name = "timethief"
for_module = "tome"
version = {1,1,5}
tags ={"class"}
weight = 100
author = { "Sebsebeleb", "seb@terminator.net" }
homepage = ""
description = [[Time thief]]
hooks = true
overload = true
superload = false
data = true